apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyototyping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyototyping
  template:
    metadata:
      labels:
        app: kyototyping
    spec:
      containers:
      - name: kyototyping
        image: docker.io/mashikotyan/kyototyping:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kyototyping-service
spec:
  selector:
    app: kyototyping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
